In [384]:
import numpy as np
import random
import math

In [3]:
field = np.zeros((9,9), dtype=int)

In [4]:
score = 0

In [5]:
field

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
def rotate_90(np_array):
    """
    A function that rotates np array 90 degrees
    """
    return np.rot90(np_array,axes=(-2,-1))

In [7]:
def generate_rotate_list(np_array):
    """
    A function that gets one array and rotates it three times
    """
    return_list = list()
    
    return_list.append(np_array)
    return_list.append(rotate_90(np_array))
    return_list.append(rotate_90(rotate_90(np_array)))
    return_list.append(rotate_90(rotate_90(rotate_90(np_array))))
    
    return return_list

In [8]:
def generate_shapes():
    """
    A function that generates all shape arrays
    There shall be 44 shapes
    """
    shape_list = list()
    t_shape_list = generate_rotate_list(np.array([[1,1,1],[0,1,0]]))
    s_shape_list = generate_rotate_list(np.array([[0,1],[1,1],[1,0]]))
    l_shape_list = generate_rotate_list(np.array([[0,1],[0,1],[1,1]])) + generate_rotate_list(np.array([[1,0],[1,0],[1,1]]))
    r_shape_list = generate_rotate_list(np.array([[1,1],[0,1]]))
    long_T_shape_list = generate_rotate_list(np.array([[1,1,1],[0,1,0]]))
    long_shape_list = [np.array([[1,1]]), np.array([[1],[1]]), np.array([[1,1,1]])
                       ,np.array([[1],[1],[1]]), np.array([[1,1,1,1]]), np.array([[1],[1],[1],[1]])
                      , np.array([[1,1,1,1,1]]), np.array([[1],[1],[1],[1],[1]])]
    big_r_shape_list = generate_rotate_list(np.array([[1,1,1],[0,0,1],[0,0,1]]))
    etc_shape_list = [np.array([1]), np.array([[1,1],[1,1]]), np.array([[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]])
                     ,np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]), np.array([[1,0,0],[0,1,0],[0,0,1]]), 
                      np.array([[0,0,1],[0,1,0],[1,0,0]]), np.array([[0,1],[1,0]]), np.array([[1,0],[0,1]])]

    shape_list += t_shape_list
    shape_list += s_shape_list
    shape_list += l_shape_list
    shape_list += r_shape_list
    shape_list += long_T_shape_list
    shape_list += long_shape_list
    shape_list += big_r_shape_list
    shape_list += etc_shape_list
    
    return shape_list

In [392]:
def game_rule(field, score):
    """
    A function that generates gamerules
    """
    field, row_score = check_rows(field)
    field, col_score = check_cols(field)
    field, block_score = check_block(field)
        
    if (row_score + col_score + block_score > 2):
        score = 18 * (row_score + col_score + block_score - 1) + 10
    elif (row_score + col_score + block_score == 1):
        score = 18
        
    #print("SCORE : " + str(score))
    
    field = clean_up(field)
    
    return field, score

In [393]:
def check_rows(field):
    """
    A function that checks row sets
    If there are any good matched ones, it will switch it to -1
    """
    row_clear = 0
    for i in range(len(field)):
        if field[i].tolist() == [1,1,1,1,1,1,1,1,1]:
            print("Cleared a ROW!")
            row_clear += 1
            field[i] = [-1,-1,-1,-1,-1,-1,-1,-1,-1]
    
    return field, row_clear

In [394]:
def check_cols(field):
    """
    A function that checks col sets
    If there are any good matched ones, it will switch it to -1
    """
    col_clear = 0
    for i in range(len(field[0])):
        cur_col = list()
        result_list = list()
        for j in range(len(field)):
            cur_col.append(field[j][i])
        for j in cur_col:
            result_list.append(j == -1 or j == 1)
        if result_list == [True, True, True, True, True, True, True, True, True]:
            print("Cleared a COL!")
            col_clear += 1
            for j in range(len(field)):
                field[j][i] = -1
            
    return field, col_clear

In [395]:
def check_block(field):
    """
    A function that checks block sets
    If there are any good matched ones, it will switch it to -1
    """
    block_clear =0
    for k in range(3):
        for i in range(3):
            cur_block = list()
            result_list = list()
            for j in range(3):
                cur_block += (field[i*3:i*3 + 3][j][k*3:k*3+3].tolist())
            for j in cur_block:
                result_list.append(j == -1 or j == 1)
            if result_list == [True, True, True, True, True, True, True, True, True]:
                for p in range(3):
                    field[i*3:i*3+3][p][k*3:k*3+3] = [-1,-1,-1]
                print("Cleared a Block!")
                block_clear += 1
    return field, block_clear

In [396]:
def clean_up(field):
    """
    A function that cleans up the field if the number is 2
    """
    field[field == -1] = 0
    return field


In [509]:
def move_shape(field, shape, x, y):
    """
    A function that moves a shape into x, y
    """
    org_field = field
    can_move, new_field = can_move_shape(field, shape, x, y)
    if (can_move):
        return True, new_field
    else:
        return False, org_field

In [510]:
def can_move_shape(field, to_move, x, y):
    """
    A function that checks if you can move a shape into a x, y
    """
    
    tmp_field = field.copy()
    if (x < 0  or y < 0):
        return False, field
    else:
        shape_size = to_move.shape
        if (x + shape_size[1] > 9 or y + shape_size[0] > 9):
            return False, field
        else:
            for i in range(shape_size[0]):
                for j in range(shape_size[1]):
                    tmp_field[i + y][j + x] = to_move[i][j] + tmp_field[i + y][j + x]
            if np.any(tmp_field > 1):
                return False, field
            else:
                return True, tmp_field

In [511]:
def is_game_over(field, to_move):
    """
    A method that determines if the game is over or not
    """
    for i in range(11):
        for j in range(11):
            if can_move_shape(field, to_move, i, j):
                return False
    return True

In [636]:
def print_screen(field):
    """
    A function that prints the field to screen
    """
    print("   0 1 2 3 4 5 6 7 8 9 10 11")
    for i in range(len(field)):
        print("%02d" % i, end='')
        for j in field[i]:
            print(" " + str(j), end='')
        print("")

In [623]:
field = np.zeros((9,9), dtype=int)
score = 0
rc = random.choice(all_shapes)

while not is_game_over(field, rc):
    print("Game Screen : ")
    print_screen(field)
    
    print("\nNew Block : ")
    print(rc)
    
    x = int(input("X : "))
    y = int(input("Y : "))
    field = move_shape(field, rc, x, y)[1]
    field, score = game_rule(field, score)
    rc = random.choice(all_shapes)
    
print("Game over...")
print("Score : " + str(score))

Game Screen : 
  0 1 2 3 4 5 6 7 8 9 10 11
0  0  0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  0
5  0  0  0  0  0  0  0  0  0
6  0  0  0  0  0  0  0  0  0
7  0  0  0  0  0  0  0  0  0
8  0  0  0  0  0  0  0  0  0

New Block : 
[[0 1 0]
 [1 1 1]]
X : 


ValueError: invalid literal for int() with base 10: ''

In [596]:
field = np.zeros((9,9), dtype=int)
score = 0
all_shapes = generate_shapes()
rc = random.choice(all_shapes)

In [597]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [598]:
def calculate_heuristics(current_field):
    game_score = game_rule(current_field, 0)[1]  # Score if put in this place
    empty_space_score = get_empty_space_group(current_field)
    connection_score = get_connection_group(current_field)
    score = game_score + (math.log10(empty_space_score)) + (math.log10(connection_score))
    
    return score

In [599]:
test_field = np.random.randint(0,2,(9,9))

In [600]:
test_field

array([[0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0]])

In [601]:
calculate_heuristics(test_field)

8.868597360437073

In [602]:
def get_empty_space_group(current_field):
    visited = np.zeros((9,9))
    total_score = 0
    for i in range(11):
        for j in range(11):
            if visited[i][j] == 1 or current_field[i][j] == 1:
                pass
            else:
                score, visited = dfs_empty_space_no_rec(current_field, visited, j, i)
                total_score += score
    return total_score

In [613]:
def get_connection_group(current_field):
    visited = np.zeros((11,11))
    total_score = 0
    for i in range(11):
        for j in range(11):
            if visited[i][j] == 1 or current_field[i][j] == 1:
                pass
            else:
                score, visited = dfs_connection_no_rec(current_field, visited, j, i)
                total_score += score
    return total_score

In [614]:
def dfs_connection_no_rec(current_field, visited, x, y):
    stack = [(x,y)]  # make stack
    score = 1  # score gets 2^n
    while (len(stack) != 0):  # if stack not empty
        cur_x, cur_y = stack.pop()  # pop
        if (cur_y > -1 and cur_x > -1) and (cur_y < 9 and cur_x < 9):
            if visited[cur_y][cur_x] == 1:  # if visited, pass
                pass  
            else :  # if not out of bound
                if current_field[cur_y][cur_x] == 1:  # and also is not filled with pixel
                    visited[cur_y][cur_x] = 1  # set visited
                    score *= 2  # score * 2
                    stack.append((cur_x, cur_y-1))  # UP
                    stack.append((cur_x, cur_y+1))  # DN
                    stack.append((cur_x-1, cur_y))  # LEFT
                    stack.append((cur_x+1, cur_y))  # RIGHT
                else:
                    pass
        else:
            pass
    return score, visited # return score

In [615]:
def dfs_empty_space_no_rec(current_field, visited, x, y):
    stack = [(x,y)]  # make stack
    score = 1  # score gets 2^n
    while (len(stack) != 0):  # if stack not empty
        cur_x, cur_y = stack.pop()  # pop
        if (cur_y > -1 and cur_x > -1) and (cur_y < 9 and cur_x < 9):
            if visited[cur_y][cur_x] == 1:  # if visited, pass
                pass  
            else :  # if not out of bound
                if current_field[cur_y][cur_x] == 0:  # and also is not filled with pixel
                    visited[cur_y][cur_x] = 1  # set visited
                    score *= 2  # score * 2
                    stack.append((cur_x, cur_y-1))  # UP
                    stack.append((cur_x, cur_y+1))  # DN
                    stack.append((cur_x-1, cur_y))  # LEFT
                    stack.append((cur_x+1, cur_y))  # RIGHT
                else:
                    pass
        else:
            pass
    return score, visited # return score

In [616]:
def generate_all_coord_scores(field, new_shape):
    all_scores = np.zeros((11,11), dtype=int)
    for i in range(11):
        for j in range(11):
            can_move, future_field = can_move_shape(field, new_shape, j, i)
            if can_move:
                all_scores[i][j] = calculate_heuristics(future_field)
            else:
                all_scores[i][j] = 0

    return all_scores

In [617]:
def generate_coordinate(all_scores):
    max_score = 0
    max_cord = (0,0)
    max_list = list()
    for i in range(11):
        for j in range(11):
            if a[i][j] >= max_score:
                max_score = a[i][j]
                max_list.append((i,j))
    
    if len(max_list) == 1:
        return (max_cord)
    else:
        return (random.choice(max_list))


In [618]:
field = np.zeros((11,11), dtype=int)
padding_field = np.pad(field, (1,1), 'constant', constant_values=1)

In [638]:
print(get_empty_space_group(padding_field))
print(get_connection_group(padding_field))

18446744073709551616
100


In [637]:
print_screen(padding_field)

   0 1 2 3 4 5 6 7 8 9 10 11
00 1 1 1 1 1 1 1 1 1 1 1 1 1
01 1 0 0 0 0 0 0 0 0 0 0 0 1
02 1 0 0 0 0 0 0 0 0 0 0 0 1
03 1 0 0 0 0 0 0 0 0 0 0 0 1
04 1 0 0 0 0 0 0 0 0 0 0 0 1
05 1 0 0 0 0 0 0 0 0 0 0 0 1
06 1 0 0 0 0 0 0 0 0 0 0 0 1
07 1 0 0 0 0 0 0 0 0 0 0 0 1
08 1 0 0 0 0 0 0 0 0 0 0 0 1
09 1 0 0 0 0 0 0 0 0 0 0 0 1
10 1 0 0 0 0 0 0 0 0 0 0 0 1
11 1 0 0 0 0 0 0 0 0 0 0 0 1
12 1 1 1 1 1 1 1 1 1 1 1 1 1


In [610]:
score = 0
rc = random.choice(all_shapes)
field, score = run_algorithm(padding_field, rc, score)

  0 1 2 3 4 5 6 7 8 9 10 11
0 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 0 0 0 0 0 0 0 0 0 0 0 1
2 1 0 0 0 0 0 0 0 0 0 0 0 1
3 1 0 0 0 0 0 0 0 0 0 0 0 1
4 1 0 0 0 0 0 0 0 0 0 0 0 1
5 1 0 0 0 0 0 0 0 0 0 0 0 1
6 1 0 0 0 0 0 0 0 0 0 0 0 1
7 1 0 0 0 0 0 0 0 0 0 0 0 1
8 1 0 0 0 0 0 0 0 0 0 0 0 1
9 1 0 0 0 0 0 0 0 0 0 0 0 1
10 1 0 0 0 0 0 0 0 0 0 0 0 1
11 1 0 0 0 0 0 0 0 0 0 0 0 1
12 1 1 1 1 1 1 1 1 1 1 1 1 1

New Block : 
[[0 1]
 [1 1]
 [1 0]]
Moving to : (4, 3)
Game Screen : 
  0 1 2 3 4 5 6 7 8 9 10 11
0 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 0 0 0 0 0 0 0 0 0 0 0 1
2 1 0 0 0 0 0 0 0 0 0 0 0 1
3 1 0 0 0 0 0 0 0 0 0 0 0 1
4 1 0 0 0 1 0 0 0 0 0 0 0 1
5 1 0 0 1 1 0 0 0 0 0 0 0 1
6 1 0 0 1 0 0 0 0 0 0 0 0 1
7 1 0 0 0 0 0 0 0 0 0 0 0 1
8 1 0 0 0 0 0 0 0 0 0 0 0 1
9 1 0 0 0 0 0 0 0 0 0 0 0 1
10 1 0 0 0 0 0 0 0 0 0 0 0 1
11 1 0 0 0 0 0 0 0 0 0 0 0 1
12 1 1 1 1 1 1 1 1 1 1 1 1 1


In [583]:
field = np.zeros((9,9), dtype=int)
score = 0
rc = random.choice(all_shapes)
field, score = run_algorithm(field, rc, score)

  0 1 2 3 4 5 6 7 8
0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0
2 0 0 0 0 0 0 0 0 0
3 0 0 0 0 0 0 0 0 0
4 0 0 0 0 0 0 0 0 0
5 0 0 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 0 0 0 0 0 0 0 0 0
8 0 0 0 0 0 0 0 0 0

New Block : 
[[1 1 1]
 [0 1 0]]
Moving to : (1, 1)
Game Screen : 
  0 1 2 3 4 5 6 7 8
0 0 0 0 0 0 0 0 0 0
1 0 1 1 1 0 0 0 0 0
2 0 0 1 0 0 0 0 0 0
3 0 0 0 0 0 0 0 0 0
4 0 0 0 0 0 0 0 0 0
5 0 0 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 0 0 0 0 0 0 0 0 0
8 0 0 0 0 0 0 0 0 0


In [566]:
def run_algorithm(field, new_shape, score):
    score_list = generate_all_coord_scores(field, new_shape)
    #print(score_list)
    coord = generate_coordinate(score_list)
    #print(coord)
    print("=====================")
    #print("BEFORE Game Screen : ")
    print_screen(field)
    
    print("\nNew Block : ")
    print(new_shape)
    print("Moving to : " + str(coord))
    field = move_shape(field, new_shape, coord[1], coord[0])[1]
    field, score = game_rule(field, score)
    
    print("Game Screen : ")
    print_screen(field)
    print("=====================")

    return field, score

In [639]:
sigmoid(54339858676587)

1.0

In [567]:
field = np.zeros((9,9), dtype=int)
score = 0
rc = random.choice(all_shapes)

while not is_game_over(field, rc):
    field, score = run_algorithm(field, rc, score)
    rc = random.choice(all_shapes)
    input("Next:")
print("Game over...")
print("Score : " + str(score))

  0 1 2 3 4 5 6 7 8
0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0
2 0 0 0 0 0 0 0 0 0
3 0 0 0 0 0 0 0 0 0
4 0 0 0 0 0 0 0 0 0
5 0 0 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 0 0 0 0 0 0 0 0 0
8 0 0 0 0 0 0 0 0 0

New Block : 
[[1 1]
 [0 1]
 [0 1]]
Moving to : (2, 5)
Game Screen : 
  0 1 2 3 4 5 6 7 8
0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0
2 0 0 0 0 0 1 1 0 0
3 0 0 0 0 0 0 1 0 0
4 0 0 0 0 0 0 1 0 0
5 0 0 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 0 0 0 0 0 0 0 0 0
8 0 0 0 0 0 0 0 0 0
Next:
  0 1 2 3 4 5 6 7 8
0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0
2 0 0 0 0 0 1 1 0 0
3 0 0 0 0 0 0 1 0 0
4 0 0 0 0 0 0 1 0 0
5 0 0 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 0 0 0 0 0 0 0 0 0
8 0 0 0 0 0 0 0 0 0

New Block : 
[[0 1]
 [1 0]]
Moving to : (1, 1)
Game Screen : 
  0 1 2 3 4 5 6 7 8
0 0 0 0 0 0 0 0 0 0
1 0 0 1 0 0 0 0 0 0
2 0 1 0 0 0 1 1 0 0
3 0 0 0 0 0 0 1 0 0
4 0 0 0 0 0 0 1 0 0
5 0 0 0 0 0 0 0 0 0
6 0 0 0 0 0 0 0 0 0
7 0 0 0 0 0 0 0 0 0
8 0 0 0 0 0 0 0 0 0
Next:
  0 1 2 3 4 5 6 7 8
0 0 0 0 0 0 0 0 0 0
1 0 0 1 0 0 0 0

KeyboardInterrupt: Interrupted by user

In [ ]:
a = generate_all_coord_scores(field, rc)

In [ ]:
g = generate_coordinate(a)

In [530]:
k = np.zeros((9,9))

In [531]:
a

array([[22, 23, 23, 23, 23, 23, 23, 23,  0],
       [23, 23, 23, 23, 23, 23, 23, 23,  0],
       [23, 23, 23, 23, 23, 23, 23, 23,  0],
       [23, 23, 23, 23, 23, 23, 23, 23,  0],
       [23, 23, 23, 23, 23, 23, 23, 23,  0],
       [23, 23, 23, 23, 23, 23, 23, 23,  0],
       [23, 23, 23, 23, 23, 23, 23, 23,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [532]:
far sides are good.

SyntaxError: invalid syntax (4202772728.py, line 1)

In [533]:
sum_list = list()
for i in g:
    sum_list.append(i[0] + i [1])

TypeError: 'int' object is not subscriptable

In [534]:
sum_list

[]